baseURL = "/"
languageCode = "pt-br"
title = "Alexandre Braga"
theme = "hugo-theme-nix"
publishDir = "../albraga.github.io"
[params]
  Name = "Alexandre Braga"
  HeaderUsername = "albraga"
  HeaderHostname = "github.io"
  About = "Analista de Sistemas"
  ProfilePicture = "https://s.gravatar.com/avatar/e0f285c1b25fb60aa80bea77c311f960?s=80"
  BitbucketID = "albraga"
  Email = "albraga@email.com"
  GithubID = "albraga"
